# Generated by Django 5.0.6 on 2024-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together={('name', 'port')},
        ),
    ]
