# Generated by Django 5.0.6 on 2024-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_app', '0002_alter_signal_name_alter_signal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together={('id', 'name', 'port')},
        ),
    ]
